### ISSUE TITLE
Could you release the preprocessing script

### ISSUE THREAD

**Issue by dido1998** [nuhaalbadi/Arabic_hatespeech#2]
I am trying to reproduce this paper. Could you provide me with the preprocessing script?

**Comment by nuhaalbadi** [comment]
Please provide me with your email so that I can send you the script as some Arabic characters used in the script won't show up here. Also,  you need one more preprocessing step after this, which is lemmatization using MADAMIRA 2.1. For that, you would have to download the software from their website.

**Comment by dido1998** [comment]
thank you very much! here is my email id:- adidolkar123@gmail.com

**Comment by arijit1410** [comment]
Hi, we are working on this project together. It seems like using the madamira lemmatizer causes the F1 scores to actually go down. We are getting a better accuracy with the ISRI stemmer itself? Can you think of reason why? Very confused.
